# Generated by Django 5.2.5 on 2025-08-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("names", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="derbyname",
            name="metadata",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
