# Generated by Django 5.2.5 on 2025-08-08 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("names", "0002_derbyname_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="DerbyJersey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="jerseys/"),
                ),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="names.derbyname",
                    ),
                ),
            ],
            options={
                "verbose_name": "Derby Jersey",
                "verbose_name_plural": "Derby Jerseys",
                "ordering": ["name"],
            },
        ),
    ]
