# Generated by Django 5.2.5 on 2025-08-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("names", "0003_derbyjersey"),
    ]

    operations = [
        migrations.AlterField(
            model_name="derbyjersey",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
